image = "/users/elyulina/store/containers/nemo_26.04_te2.15.sqsh"

mounts = ["/capstor", "/iopsstor", "/users"]
writable = true
workdir = "/workspace"

[annotations]
com.hooks.aws_ofi_nccl.enabled = "true"
com.hooks.aws_ofi_nccl.variant = "cuda13"